// <auto-generated />
namespace AspNetIdentity.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClinicaLogo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClinicaLogo));
        
        string IMigrationMetadata.Id
        {
            get { return "201508290153159_ClinicaLogo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
